export const REQUEST_CALL_DATA = "REQUEST_CALL_DATA";
export const SET_CALL_DATA = "SET_CALL_DATA";
export const SET_CALL_DATA_FAILED = "SET_CALL_DATA_FAILED";
export const SET_ALL_CALL_ARCHIVE = "SET_ALL_CALL_ARCHIVE";
export const SET_ALL_CALL_UNARCHIVE = "SET_ALL_CALL_UNARCHIVE";
